# Generated by Django 3.1 on 2020-08-09 15:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertool', '0002_auto_20200809_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjob',
            name='deadlinedate',
            field=models.DateTimeField(help_text='Enter the date of purchase', validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime.now)]),
        ),
    ]
