# Generated by Django 3.1 on 2020-08-08 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ordertool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('deadlinedate', models.DateField()),
                ('completeddate', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('newzip', models.FileField(upload_to=ordertool.models.user_directory_path)),
                ('examplezip', models.FileField(blank=True, upload_to=ordertool.models.user_directory_path)),
                ('status', models.CharField(choices=[('neworder', 'New Order'), ('running', 'Running'), ('QC', 'Quality Check'), ('shipped', 'Shipped to Customer'), ('completed', 'Order Completed'), ('Do more', 'Do More'), ('Redo', 'Redo')], default='neworder', max_length=9)),
                ('jobcreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
