# Generated by Django 3.1 on 2020-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertool', '0002_auto_20200808_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjob',
            name='amountimages',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
