# Generated by Django 3.1 on 2020-08-09 15:15

from django.db import migrations, models
import ordertool.models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertool', '0003_userjob_amountimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjob',
            name='idxml',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userjob',
            name='deadlinedate',
            field=models.DateTimeField(help_text='Enter the date of purchase', validators=[ordertool.models.no_past]),
        ),
    ]
